language: node_js
deploy:
  api_key:
    secure: k8ysX0XKfyLxZ8xkVC5GPygXw/m4SikZb/IyjLPYUMUEXXVKL7+a2wLZytwnAAq0nE4Z7Ofp+MlbxMvtyXxLXXDCkbTYcvNt6cupyTjinMYP/8u6dofEXHfZQlxt4Xd3+765wpEcYJGmlmtdaBTB7gI0FTAdzbwNoOGzgeCNR+8=
  provider: npm
  email: john@mclear.co.uk
